/// <reference path="./microsim.d.ts"/>


namespace MicroSim{
	export class DisplayDevice2C02 implements MicroSim.DisplayDevice{
		_2c02 : Module.MemoryDevice2C02;
		_canvas : HTMLCanvasElement;
		_dragable: Dragable;
		_ctx : CanvasRenderingContext2D;
		_colors : Uint8Array;
		_display_buf : Uint8Array;
		constructor(freq:number=3000000){
			this._canvas = document.createElement("canvas");
			this._canvas.classList.add("dragable", "handle");
			this._canvas.width = 256;
			this._canvas.height = 240;
			this._dragable = new Dragable(this._canvas);
			this._ctx = this._canvas.getContext("2d");
			this.gen_colors();
			document.body.append(this._canvas);

			this._2c02 = new Module.MemoryDevice2C02(freq);
			let refresh_fn = addFunction(this.refresh.bind(this), 'v');
			this._2c02.set_refresh_fn(refresh_fn);

		}
		refresh(){
			this._display_buf = this._2c02.display();
			let img = new ImageData(256, 240);
			for(let i = 0; i < 256*240; i++){
				let val = this._display_buf[i];
				for(let j = 0; j < 4; j++)
					img.data[i*4+j] = this._colors[val*4+j];
			}
			this._ctx.putImageData(img, 0, 0);
		}
		memory_devices(){
			return [this._2c02];
		}

		gen_colors(){
			this._colors = new Uint8Array(256);
			let i = 0;
			const ALPHA = 255;
			this._colors[i++] = 84;
			this._colors[i++] = 84;
			this._colors[i++] = 84;
			this._colors[i++] = ALPHA;    
			this._colors[i++] = 0;
			this._colors[i++] = 30;
			this._colors[i++] = 116;
			this._colors[i++] = ALPHA;    
			this._colors[i++] = 8;
			this._colors[i++] = 16;
			this._colors[i++] = 144;
			this._colors[i++] = ALPHA;   
			this._colors[i++] = 48;
			this._colors[i++] = 0;
			this._colors[i++] = 136;
			this._colors[i++] = ALPHA;   
			this._colors[i++] = 68;
			this._colors[i++] = 0;
			this._colors[i++] = 100;
			this._colors[i++] = ALPHA;   
			this._colors[i++] = 92;
			this._colors[i++] = 0;
			this._colors[i++] = 48;
			this._colors[i++] = ALPHA;   
			this._colors[i++] = 84;
			this._colors[i++] = 4;
			this._colors[i++] = 0;
			this._colors[i++] = ALPHA;   
			this._colors[i++] = 60;
			this._colors[i++] = 24;
			this._colors[i++] = 0;
			this._colors[i++] = ALPHA;   
			this._colors[i++] = 32;
			this._colors[i++] = 42;
			this._colors[i++] = 0;
			this._colors[i++] = ALPHA;    
			this._colors[i++] = 8;
			this._colors[i++] = 58;
			this._colors[i++] = 0;
			this._colors[i++] = ALPHA;    
			this._colors[i++] = 0;
			this._colors[i++] = 64;
			this._colors[i++] = 0;
			this._colors[i++] = ALPHA;    
			this._colors[i++] = 0;
			this._colors[i++] = 60;
			this._colors[i++] = 0;
			this._colors[i++] = ALPHA;    
			this._colors[i++] = 0;
			this._colors[i++] = 50;
			this._colors[i++] = 60;
			this._colors[i++] = ALPHA;    
			this._colors[i++] = 0;
			this._colors[i++] = 0;
			this._colors[i++] = 0;
			this._colors[i++] = ALPHA;   
			this._colors[i++] = 0;
			this._colors[i++] = 0;
			this._colors[i++] = 0;
			this._colors[i++] = ALPHA;   
			this._colors[i++] = 0;
			this._colors[i++] = 0;
			this._colors[i++] = 0;
			this._colors[i++] = ALPHA;

			this._colors[i++] = 152;
			this._colors[i++] = 150;
			this._colors[i++] = 152;
			this._colors[i++] = ALPHA;    
			this._colors[i++] = 8;
			this._colors[i++] = 76;
			this._colors[i++] = 196;
			this._colors[i++] = ALPHA;   
			this._colors[i++] = 48;
			this._colors[i++] = 50;
			this._colors[i++] = 236;
			this._colors[i++] = ALPHA;   
			this._colors[i++] = 92;
			this._colors[i++] = 30;
			this._colors[i++] = 228;
			this._colors[i++] = ALPHA;  
			this._colors[i++] = 136;
			this._colors[i++] = 20;
			this._colors[i++] = 176;
			this._colors[i++] = ALPHA;  
			this._colors[i++] = 160;
			this._colors[i++] = 20;
			this._colors[i++] = 100;
			this._colors[i++] = ALPHA;  
			this._colors[i++] = 152;
			this._colors[i++] = 34;
			this._colors[i++] = 32;
			this._colors[i++] = ALPHA;  
			this._colors[i++] = 120;
			this._colors[i++] = 60;
			this._colors[i++] = 0;
			this._colors[i++] = ALPHA;   
			this._colors[i++] = 84;
			this._colors[i++] = 90;
			this._colors[i++] = 0;
			this._colors[i++] = ALPHA;   
			this._colors[i++] = 40;
			this._colors[i++] = 114;
			this._colors[i++] = 0;
			this._colors[i++] = ALPHA;    
			this._colors[i++] = 8;
			this._colors[i++] = 124;
			this._colors[i++] = 0;
			this._colors[i++] = ALPHA;    
			this._colors[i++] = 0;
			this._colors[i++] = 118;
			this._colors[i++] = 40;
			this._colors[i++] = ALPHA;    
			this._colors[i++] = 0;
			this._colors[i++] = 102;
			this._colors[i++] = 120;
			this._colors[i++] = ALPHA;    
			this._colors[i++] = 0;
			this._colors[i++] = 0;
			this._colors[i++] = 0;
			this._colors[i++] = ALPHA; 
			this._colors[i++] = 0;
			this._colors[i++] = 0;
			this._colors[i++] = 0;
			this._colors[i++] = ALPHA;   
			this._colors[i++] = 0;
			this._colors[i++] = 0;
			this._colors[i++] = 0;
			this._colors[i++] = ALPHA;

			this._colors[i++] = 236;
			this._colors[i++] = 238;
			this._colors[i++] = 236;
			this._colors[i++] = ALPHA;   
			this._colors[i++] = 76;
			this._colors[i++] = 154;
			this._colors[i++] = 236;
			this._colors[i++] = ALPHA;  
			this._colors[i++] = 120;
			this._colors[i++] = 124;
			this._colors[i++] = 236;
			this._colors[i++] = ALPHA;  
			this._colors[i++] = 176;
			this._colors[i++] = 98;
			this._colors[i++] = 236;
			this._colors[i++] = ALPHA;  
			this._colors[i++] = 228;
			this._colors[i++] = 84;
			this._colors[i++] = 236;
			this._colors[i++] = ALPHA;  
			this._colors[i++] = 236;
			this._colors[i++] = 88;
			this._colors[i++] = 180;
			this._colors[i++] = ALPHA;  
			this._colors[i++] = 236;
			this._colors[i++] = 106;
			this._colors[i++] = 100;
			this._colors[i++] = ALPHA;  
			this._colors[i++] = 212;
			this._colors[i++] = 136;
			this._colors[i++] = 32;
			this._colors[i++] = ALPHA;  
			this._colors[i++] = 160;
			this._colors[i++] = 170;
			this._colors[i++] = 0;
			this._colors[i++] = ALPHA;  
			this._colors[i++] = 116;
			this._colors[i++] = 196;
			this._colors[i++] = 0;
			this._colors[i++] = ALPHA;   
			this._colors[i++] = 76;
			this._colors[i++] = 208;
			this._colors[i++] = 32;
			this._colors[i++] = ALPHA;   
			this._colors[i++] = 56;
			this._colors[i++] = 204;
			this._colors[i++] = 108;
			this._colors[i++] = ALPHA;   
			this._colors[i++] = 56;
			this._colors[i++] = 180;
			this._colors[i++] = 204;
			this._colors[i++] = ALPHA;   
			this._colors[i++] = 60;
			this._colors[i++] = 60;
			this._colors[i++] = 60;
			this._colors[i++] = ALPHA; 
			this._colors[i++] = 0;
			this._colors[i++] = 0;
			this._colors[i++] = 0;
			this._colors[i++] = ALPHA;   
			this._colors[i++] = 0;
			this._colors[i++] = 0;
			this._colors[i++] = 0;
			this._colors[i++] = ALPHA;

			this._colors[i++] = 236;
			this._colors[i++] = 238;
			this._colors[i++] = 236;
			this._colors[i++] = ALPHA;  
			this._colors[i++] = 168;
			this._colors[i++] = 204;
			this._colors[i++] = 236;
			this._colors[i++] = ALPHA;  
			this._colors[i++] = 188;
			this._colors[i++] = 188;
			this._colors[i++] = 236;
			this._colors[i++] = ALPHA;  
			this._colors[i++] = 212;
			this._colors[i++] = 178;
			this._colors[i++] = 236;
			this._colors[i++] = ALPHA;  
			this._colors[i++] = 236;
			this._colors[i++] = 174;
			this._colors[i++] = 236;
			this._colors[i++] = ALPHA;  
			this._colors[i++] = 236;
			this._colors[i++] = 174;
			this._colors[i++] = 212;
			this._colors[i++] = ALPHA;  
			this._colors[i++] = 236;
			this._colors[i++] = 180;
			this._colors[i++] = 176;
			this._colors[i++] = ALPHA;  
			this._colors[i++] = 228;
			this._colors[i++] = 196;
			this._colors[i++] = 144;
			this._colors[i++] = ALPHA;  
			this._colors[i++] = 204;
			this._colors[i++] = 210;
			this._colors[i++] = 120;
			this._colors[i++] = ALPHA;  
			this._colors[i++] = 180;
			this._colors[i++] = 222;
			this._colors[i++] = 120;
			this._colors[i++] = ALPHA;  
			this._colors[i++] = 168;
			this._colors[i++] = 226;
			this._colors[i++] = 144;
			this._colors[i++] = ALPHA;  
			this._colors[i++] = 152;
			this._colors[i++] = 226;
			this._colors[i++] = 180;
			this._colors[i++] = ALPHA;  
			this._colors[i++] = 160;
			this._colors[i++] = 214;
			this._colors[i++] = 228;
			this._colors[i++] = ALPHA;  
			this._colors[i++] = 160;
			this._colors[i++] = 162;
			this._colors[i++] = 160;
			this._colors[i++] = ALPHA; 
			this._colors[i++] = 0;
			this._colors[i++] = 0;
			this._colors[i++] = 0;
			this._colors[i++] = ALPHA;   
			this._colors[i++] = 0;
			this._colors[i++] = 0;
			this._colors[i++] = 0;
			this._colors[i++] = ALPHA;
		}
	}
}